### ISSUE TITLE
Download and starting problems

### ISSUE THREAD

**Issue by Arytas** [relu91/niftyeditor#25] opened 2015-09-30 06:54 UTC
Hi there,

i have some trouble with your Editor.
First thing, the Download for the "JME plugin 0.5.9 alpha" is defect for me. There is no dl, only the code in crypts :)
http://niftyeditor.it/download/5/

the other thing, if i download the "Nifty-Editor v0.6 SOC edition" i can start it, but cant use anything inside (except create, delete ... new files)
i use linux dist (fedora22) and openjdk 1.8.0_60-b27 
when i start the jar file, i get this Warnings in the console ->> http://pastebin.com/fcwBTdBU

**Comment by Arytas** [comment] 2015-10-02 08:47
hm maybe its a problem on my side
cause i also have trouble with the minecraft technic launcher (graphic is buggy in the launcher)

**Comment by relu91** [comment] 2016-01-08 20:24
Can't reproduce, if you confirm that it was your problem I'll close this one.

**Comment by Arytas** [comment] 2016-06-13 08:40
yes was problem on my side

**Closed as completed** 2016-06-24 08:46 UTC
